# 1. Conexión con MySQL
spring.datasource.url=jdbc:mysql://bqvm2de3wziaoxbfls7l-mysql.services.clever-cloud.com:3306/bqvm2de3wziaoxbfls7l?serverTimezone=UTC
spring.datasource.username=u6puchcorrmrel21
spring.datasource.password=c00q7BBKENTQiVf1O3T9

# 2. Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Formato de Logs (Opcional, para verlo todo más claro)
logging.level.org.hibernate.SQL=DEBUG