# 1. Conexión con MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/programmer_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# 2. Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Formato de Logs (Opcional, para verlo todo más claro)
logging.level.org.hibernate.SQL=DEBUG